"""empty message

Revision ID: 076698506c6f
Revises: e20e525120a9
Create Date: 2021-08-20 02:38:56.649115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076698506c6f'
down_revision = 'e20e525120a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('character_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'character_id')
    # ### end Alembic commands ###
