"""empty message

Revision ID: b51f8da9d74c
Revises: e9635b8ecab7
Create Date: 2021-08-20 04:05:30.260853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51f8da9d74c'
down_revision = 'e9635b8ecab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_index('email_2', table_name='user')
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=False)
    op.create_index('email_2', 'user', ['email'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
