"""empty message

Revision ID: b9fc73668609
Revises: bd47b019a27b
Create Date: 2021-08-24 00:59:29.705990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9fc73668609'
down_revision = 'bd47b019a27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite', 'character_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite', 'vehicle_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite', 'vehicle_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite', 'character_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
