"""empty message

Revision ID: eb9cb8243358
Revises: 564dc70154f0
Create Date: 2021-08-20 05:16:54.118741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9cb8243358'
down_revision = '564dc70154f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='vehicle')
    op.drop_index('name_2', table_name='vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_2', 'vehicle', ['name'], unique=False)
    op.create_index('name', 'vehicle', ['name'], unique=False)
    # ### end Alembic commands ###
